# give all definition sources the @en language.

PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX obo: <http://purl.obolibrary.org/obo/>

DELETE {
  ?def_annot obo:IAO_0000119 ?subValue
}
INSERT {
  ?def_annot obo:IAO_0000119 ?subValue_en
}
WHERE {
  ?class a owl:Class .
  OPTIONAL {
    ?class obo:IAO_0000115 ?annValue .
    ?def_annot owl:annotatedSource ?class ;
    owl:annotatedProperty obo:IAO_0000115 ;
    owl:annotatedTarget ?annValue ;
    obo:IAO_0000119 ?subValue .
    BIND(IF(LANG(?subValue) = "", STRLANG(?subValue, "en"), ?subValue) AS ?subValue_en)
  }
}
