# give all annotation properties the @en language.

PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

DELETE {
  ?class ?property ?annValue
}
INSERT {
  ?class ?property ?annValue_en
}
WHERE {
  ?class a owl:Class .
  ?class ?property ?annValue .
  {?property a owl:AnnotationProperty} UNION {?property a rdfs:comment}
  BIND(IF(LANG(?annValue) = "", STRLANG(?annValue, "en"), ?annValue) AS ?annValue_en)
}
