PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT { ?s ?p ?o ;
			   oboInOwl:hasExactSynonym ?label .
			?p a owl:AnnotationProperty ;
			   rdfs:label ?apLabel . }
WHERE     { ?s a owl:Class ;
			   obo:T4FS_9000001 ?browserLabel ;
			   rdfs:label ?label ;
			   ?p ?o .
			?p a owl:AnnotationProperty .
			FILTER (?p != rdfs:label)
			FILTER (?p != obo:T4FS_9000001)
			FILTER (?p != obo:T4FS_9000000)
			FILTER (?p != oboInOwl:hasDbXref)
			OPTIONAL { ?p rdfs:label ?apLabel . } }
