PREFIX owl: <http://www.w3.org/2002/07/owl#>

DELETE { ?s ?p ?o }
WHERE  { ?s ?p ?o .
		 ?p a owl:AnnotationProperty .
		 FILTER (LANG(?o) != "")
		 FILTER (LANG(?o) != "en") 
	   } ;

DELETE { ?s ?p ?o }
WHERE  { ?s ?p ?o .
		 ?s ?p ?o2 .
		 ?p a owl:AnnotationProperty .
		 FILTER (LANG(?o) != "")
		 FILTER (LANG(?o2) != "en") 
	   } ;
